# Generated by Django 5.1 on 2024-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0004_alter_category_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
