POST http://localhost:8000/signup/
Content-Type: application/json

{"username": "admin","email": "myawesomeemail@wolfontheweb.com","password": "pass1234!"}

###

POST http://localhost:8000/login/
Content-Type: application/json

{"username": "admin", "password": ""}

###

GET  http://localhost:8000/tokentest/
Content-Type: application/json
Authorization: Token 650d817c335fe15bf5e23aebbc146e9284b9b387

###

GET http://localhost:8000/posts/
Content-Type: application/json
Authorization: Token 650d817c335fe15bf5e23aebbc146e9284b9b387

###

GET http://localhost:8000/posts/
Content-Type: application/json

###

POST http://localhost:8000/posts/
Content-Type: application/json
Authorization: Token 9e6b927750a11cf47715fd9a22851cb2301674e6

{"title": "post for test user 22", "body": "hello2u", "categories": []}

###

PUT http://localhost:8000/posts/14/
Content-Type: application/json
Authorization: Token 9e6b927750a11cf47715fd9a22851cb2301674e6

{"title": "post for test user 22", "body": "updated body", "isPublished": true, "categories": []}

###

DELETE http://localhost:8000/posts/7/
Content-Type: application/json
Authorization: Token 650d817c335fe15bf5e23ae6e9284b9b387


###

POST http://localhost:8000/categories/
Content-Type: application/json
Authorization: Token 9e6b927750a11cf47715fd9a22851cb2301674e6

{"name": "programming"}

###

GET http://localhost:8000/categories/
Content-Type: application/json